springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs
server:
  servlet:
    contextPath: /VjFullStack/BankingAPI/1.0.0
  port: 8091
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.banking.chatbot.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create

  datasource:
    url: jdbc:h2:mem:bankingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    root: info

