springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs
server:
  servlet:
    contextPath: /VjFullStack/BankingAPI/1.0.0
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.banking.chatbot.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankingdb
    username: root
    password: admin12345
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
  file: logs/application.log