  /**
    * Application configuration file.
    *
    * @author Viraj Salokhe
    */
springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs
server:
  servlet:
    contextPath: /VjFullStack/BankingAPI/1.0.0
  port: 5000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: com.banking.chatbot.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  datasource:
      url: jdbc:mysql://bankingdb.cccz3f0c6l76.ap-northeast-1.rds.amazonaws.com:3306/bankingdb
      username: admin
      password: admin12345
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: aws
#    aws:
#      jpa:
#        show-sql: false
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.MySQL5Dialect
#        hibernate:
#          ddl-auto: create-drop
#      datasource:
#        url: bankingdb.cccz3f0c6l76.ap-northeast-1.rds.amazonaws.com
#        username: admin
#        password: admin12345
#        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
  file: logs/application.log
